sudo: required
language: go
go:
  - 1.6

env:
  - PLATFORM=android-arm
  - PLATFORM=android-x64
  - PLATFORM=android-x86
  - PLATFORM=darwin-x64
  - PLATFORM=linux-x64
  - PLATFORM=linux-x86
  - PLATFORM=linux-arm
  - PLATFORM=windows-x64
  - PLATFORM=windows-x86

services:
  - docker

install:
  - make env

script:
  - make $PLATFORM
